<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Str;
use Laravel\Sanctum\HasApiTokens;
use Illuminate\Database\Eloquent\Relations\HasMany;

/**
 * @method static where(string $string, $token)
 */
class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * 给user实体类定义字段账户激活令牌
     *
     * @return void
     */
    public static function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function ($user) {
            $user->activation_token= Str::random(10);
        });
    }

    public function gravatar($size = 100): string
    {
        $hash = md5(strtolower(trim($this->attributes['email'])));
//        return "https://www.gravatar.com/avatar/$hash?s=$size";
        return "https://cdn.v2ex.com/gravatar/$hash?s=$size";
    }

    /**
     * 用户表与微博用户表关联，1个用户拥有多条微博
     *
     * @return HasMany
     */
    public function statuses(): HasMany
    {
        return $this->hasMany(Status::class);
    }


    /**
     * 获取当前用户和已关注用户发布的微博
     *
     * @return mixed
     */
    public function feed(): mixed
    {
        $user_ids=$this->followings->pluck('id')->toArray();
        $user_ids[] = $this->id;
        return Status::whereIn('user_id',$user_ids)
            ->with('user')
            ->orderBy('created_at','desc');
    }

    /**
     * 用户被关注了
     *
     * @return BelongsToMany
     */
    public function followers(): BelongsToMany
    {
        return $this->belongsToMany(User::class, 'followers', 'user_id', 'follower_id');
    }

    /**
     *用户关注了哪些用户，1对多
     *
     * @return BelongsToMany
     */
    public function followings(): BelongsToMany
    {
        return $this->belongsToMany(User::class, 'followers', 'follower_id', 'user_id');
    }


    /**
     * 关注
     *
     * @param $user_ids
     * @return void
     */
    public function follow($user_ids): void
    {
        if (!is_array($user_ids)) {
            $user_ids = compact('user_ids');
        }
        $this->followings()->sync($user_ids, false);
    }

    /**
     * 取消关注
     *
     * @param $user_ids
     * @return void
     */
    public function unfollow($user_ids): void
    {
        if (!is_array($user_ids)) {
            $user_ids = compact('user_ids');
        }
        $this->followings()->detach($user_ids);
    }

    /**
     * 是否关注了某个用户, $user_id 是要检查的用户 id
     * contains 方法是 Collection 类的一个方法，用来判断一个集合是否包含某个元素
     * 成功返回 true，失败返回 false
     *
     * @param $user_id
     * @return bool
     */
    public function isFollowing($user_id):bool
    {
        return $this->followings->contains($user_id);
    }



}
